### ISSUE TITLE
Unexpected import path in the buildfs subpackage.

### ISSUE THREAD

**Issue by dmitshur** [rainycape/vfs#1]
Hi,

The README suggests that the canonical import path of this package is `gopkgs.com/vfs.v1`.

When I do `go get -u gopkgs.com/vfs.v1`, and then cd into that folder, there's a subpackage `buildfs`.

It imports `gopkgs.com/gh/rainycape/vfs`. This seems to be via source code rewriting done by gopkgs.com since the github source [here](https://github.com/rainycape/vfs/blob/63ad8bb0bc73ade183be47951b75513bf690c1d0/buildfs/buildfs.go#L11) has it importing `github.com/rainycape/vfs`.

So now my GOPATH workspace has both `gopkgs.com/vfs.v1` and `gopkgs.com/gh/rainycape/vfs`. When I cd into that folder, it also has a `buildfs` subpackage, which imports `gopkgs.com/gh/rainycape/vfs`.

Is this intentional? If `gopkgs.com/vfs.v1` is supposed to be the canonical import path, shouldn't `buildfs` package import `gopkgs.com/vfs.v1`? Or is `gopkgs.com/gh/rainycape/vfs` the actual canonical import path and the README is outdated?

**Comment by dmitshur** [comment]
I think this is related to rainycape/gopkgs#1, which has been open and unanswered since October 2014.

**Comment by dmitshur** [comment]
Also, is the source of http://gopkgs.com/ available somewhere, or is it closed source? Is there a way I can report an issue?

**Comment by terinjokes** [comment]
@shurcooL Looks like it's gopkgs is no longer recommended

**Comment by dmitshur** [comment]
@terinjokes Do you have a source for that?

**Comment by rainycape** [comment]
@terinjokes @shurcooL I'll update the package to stop forcing the import path from gopkgs.com

As @terinjokes has pointed out, I'm discontinuing gopkgs in the coming weeks because someone has been DDoS'ing it for a couple of weeks and I don't have the time to deal with that.

**Comment by dmitshur** [comment]
This is issue has been resolved in a62fd22bcf7010946a44f6a1250a82c03110a14b, closing.
